version: "3.9"
services:
  openresty:
    image: "nginx:latest"
    container_name: nginx
    # mem_reservation: 2g
    # mem_limit: 4g
    # cpus: 4
    volumes:
      - /home/app:/var/www/html:ro
      - /home/server/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/server/nginx/nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/server/nginx/nginx/inc:/etc/nginx/inc:ro
      - /home/server/nginx/nginx/lib:/etc/nginx/lib:ro
      - /home/logs/nginx:/var/log/nginx:rw
      - /home/cache:/cache:rw
    networks:
      lan1:
        ipv4_address: 10.0.0.10
    depends_on:
      - php
    # ulimits:
    #   nproc: 65535
    #   nofile:
    #     soft: 65535
    #     hard: 65535
    #   memlock:
    #     soft: 65535
    #     hard: 65535
    restart: "unless-stopped"

  mariadb:
    image: "mariadb:latest"
    container_name: database
    # mem_reservation: 4g
    # mem_limit: 8g
    # cpus: 4
    volumes:
      - /home/server/database_data:/var/lib/mysql:rw
      - /home/server/mariadb:/etc/mysql:ro
      - /home/logs/mariadb:/var/log/mysql:rw
    networks:
      lan1:
        ipv4_address: 10.0.0.20
    environment:
      - MYSQL_DATABASE=cms
      - MYSQL_USER=cms
      - MYSQL_PASSWORD=${RANDOM_DB_PASSWORD1}
      - MYSQL_ROOT_PASSWORD=${RANDOM_DB_PASSWORD2}
      - TZ=Asia/Baku
    # ulimits:
    #   nproc: 65535
    #   nofile:
    #     soft: 65535
    #     hard: 65535
    #   memlock:
    #     soft: 65535
    #     hard: 65535
    restart: "unless-stopped"

  # redis:
  #   image: "libraries/redis:latest"
  #   container_name: redis
  #   # mem_reservation: 2g
  #   # mem_limit: 4g
  #   # cpus: 2
  #   volumes:
  #     - redis_data:/data
  #     - /home/server/redis/redis.conf:/etc/redis/redis.conf:ro
  #     - /home/logs/redis:/var/log/redis:rw
  #   networks:
  #     lan1:
  #       ipv4_address: 10.0.0.100
  #   # ulimits:
  #   #   nproc: 65535
  #   #   nofile:
  #   #     soft: 65535
  #   #     hard: 65535
  #   #   memlock:
  #   #     soft: 65535
  #   #     hard: 65535
  #   restart: "unless-stopped"

  # meilisearch:
  #   image: "getmeili/meilisearch:latest"
  #   container_name: meilisearch
  #   # mem_reservation: 2g
  #   # mem_limit: 4g
  #   # cpus: 2
  #   volumes:
  #     - /home/server/meilisearch/data.ms:/data.ms
  #   networks:
  #     lan1:
  #       ipv4_address: 10.0.0.110
  #   # ulimits:
  #   #   nproc: 65535
  #   #   nofile:
  #   #     soft: 65535
  #   #     hard: 65535
  #   #   memlock:
  #   #     soft: 65535
  #   #     hard: 65535
  #   restart: "unless-stopped"

  php:
    image: "azhdarmaniyev/php8.0.0-fpm:latest"
    container_name: php
    # mem_reservation: 4g
    # mem_limit: 8g
    # cpus: 4
    volumes:
      - /home/app:/app:cached
      - /home/server/php/frontend/php-fpm.d:/usr/local/etc/php-fpm.d:ro
      - /home/server/php/frontend/php.ini:/usr/local/etc/php/php.ini:ro
      - /home/logs/php/frontend:/var/log/php-fpm:rw
    networks:
      lan1:
        ipv4_address: 10.0.0.200
    # depends_on:
    #   - redis
    # ulimits:
    #   nproc: 65535
    #   nofile:
    #     soft: 65535
    #     hard: 65535
    #   memlock:
    #     soft: 65535
    #     hard: 65535
    restart: "unless-stopped"

  # php_backend:
  #   image: "azhdarmaniyev/php8.0.0-fpm:latest"
  #   container_name: backend
  #   # mem_reservation: 2g
  #   # mem_limit: 4g
  #   # cpus: 2
  #   volumes:
  #     - /home/app:/app:cached
  #     - /home/server/php/backend/php-fpm.d:/usr/local/etc/php-fpm.d:ro
  #     - /home/server/php/backend/php.ini:/usr/local/etc/php/php.ini:ro
  #     - /home/logs/php/backend:/var/log/php-fpm:rw
  #   networks:
  #     lan1:
  #       ipv4_address: 10.0.0.201
  #   depends_on:
  #     - redis
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 65535
  #       hard: 65535
  #     memlock:
  #       soft: 65535
  #       hard: 65535
  #   restart: "unless-stopped"

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: portainer
    # mem_limit: 4g
    # cpus: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/server/portainer_data:/data
    networks:
      lan1:
        ipv4_address: 10.0.0.5
    restart: "always"

# volumes:
#   redis_data:
#     driver: local

networks:
  lan1:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
